[[apps]]
name = "YouTube"
url = "https://www.youtube.com"
image = "images/youtube.png"

[[apps]]
name = "Plex"
url = "http://192.168.1.100:32400/web"
image = "images/plex.png"

[[apps]]
name = "Spotify"
url = "https://open.spotify.com"
image = "images/spotify.png"

[[apps]]
name = "Web"
url = "https://start.duckduckgo.com/"
image = "images/web.jpeg"
address_bar = true